FROM maven:3.9.6-eclipse-temurin-17 AS build
LABEL authors="hendisantika"

WORKDIR /app

COPY ./pom.xml .

RUN mvn dependency:go-offline -B

COPY ./src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine AS final

WORKDIR /app

COPY --from=build /app/target/*.jar gatewayserver.jar

EXPOSE 9000

ENTRYPOINT ["java", "-jar", "gatewayserver.jar"]